name: flowrules_build

on: [push]

env:
  BuildConfiguration: Release
  NugetPackagePath: $HOME/nuget
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Fetch git history
      run: git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
          versionSpec: '6.0.5'

    - name: Determine semantic version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '9.x'

    - name: dotnet clean
      run: dotnet clean src

    - name: dotnet build
      run: dotnet build src/FlowRules.sln --configuration ${{ env.BuildConfiguration }} /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }};AssemblyFileVersion=${{ steps.gitversion.outputs.AssemblySemVer }};AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }};AssemblyInformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}

    - name: dotnet test 
      run: dotnet test src --logger:"trx;LogFileName=TestResults.xml" --filter Category!=Extension --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --configuration ${{ env.BuildConfiguration }} 

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests            
        path: ./**/TestResults.xml 
        reporter: dotnet-trx       

    - name: Publish coverage report to codecov.io (UNIT)
      uses: codecov/codecov-action@v2
      with:
        file: coverage.opencover.xml
        directory: src/FlowRules.Engine.UnitTests
        token: ${{ secrets.CODECOV_TOKEN  }}
        flags: unit

    - name: nuget packaging
      run: |
            dotnet pack src/FlowRules.Engine/FlowRules.Engine.csproj --no-build --include-symbols -o ${{ env.NugetPackagePath }} -p:Configuration=${{ env.BuildConfiguration }} -p:Version=${{ steps.gitversion.outputs.FullSemVer }};SymbolPackageFormat=snupkg            
            dotnet pack src/FlowRules.Extensions.SqlServer/FlowRules.Extensions.SqlServer.csproj --no-build --include-symbols -o ${{ env.NugetPackagePath }} -p:Configuration=${{ env.BuildConfiguration }} -p:Version=${{ steps.gitversion.outputs.FullSemVer }};SymbolPackageFormat=snupkg
            echo "VERSION=${{ steps.gitversion.outputs.FullSemVer }}" >> $GITHUB_ENV
            ls ${{ env.NugetPackagePath }}/*
            echo "${{ steps.gitversion.outputs.FullSemVer }}" > ${{ env.NugetPackagePath }}/version.txt

    - name: Setup nuget.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    - name: list packages
      run: ls -l /home/runner/nuget

    - name: Upload nuget packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget_packages
        path: /home/runner/nuget

  publish-packages:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: download
        uses: actions/download-artifact@v4
        with:
          name: nuget_packages
          path: ./nuget_packages

      - name: Extract version from artifact
        run: |
            ls ./nuget_packages/*
            version=`cat ./nuget_packages/version.txt`
            echo "VERSION=$version" >> $GITHUB_ENV

      - name: Push generated package to GitHub registry
        if: contains(github.ref, 'develop') || contains(github.ref, 'releases')
        run: |
          dotnet nuget push ./nuget_packages/*.nupkg --source "https://nuget.pkg.github.com/p1971/index.json" --skip-duplicate --api-key ${{secrets.GITHUB_TOKEN}}          
        shell: bash

      - name: Push generated package to Nuget registry
        if: contains(github.ref, 'main')
        run: |
          dotnet nuget push ./nuget_packages/*.nupkg --source "https://api.nuget.org/v3/index.json" --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}          
        shell: bash

      - name: Create Release
        if: contains(github.ref, 'main')
        id: create_release
        uses: ncipollo/release-action@v1        
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./nuget_packages/*"
          tag: ${{ env.VERSION }} 
